language: cpp

os:
  - linux
  - osx

compiler:  
    - gcc
    - clang

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make  

deploy:
    - skip_cleanup: true
    - provider: releases
    - api_key: "GITHUB OAUTH TOKEN"
    - file: "FILE TO UPLOAD"
    - skip_cleanup: true
    - on:
    - tags: true
  