version: 1.0.{build}

#branches:
    #only:
#      - master

install:
  - ps: wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-win32-x86.zip -OutFile cmake.zip
  - cmd: echo "Unzipping cmake..."
  - cmd: 7z x cmake.zip -o"C:\Program Files (x86)\" -y > nul
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\Program Files (x86)\cmake-3.0.2-win32-x86\bin
  - cmd: cmake --version
  - cmd: del cmake.zip
  
environment:
  matrix:
    - GENERATOR: "Visual Studio 12"
      CONFIG: Debug

    #- GENERATOR: "Visual Studio 12"
      #CONFIG: Release

build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"

test_script:
  - ps: cd _builds
  - ctest -VV -C "%CONFIG%"
  - ps: cd ..

after_build:
  - ECHO ON
  - mkdir travis-ci-cpp-test
  - xcopy _builds\%CONFIG%\TravisCITest.exe travis-ci-cpp-test
  
  - 7z a travis-ci-cpp-test_%CONFIG%.zip travis-ci-cpp-test\*.*
  - dir

artifacts:
  - path: travis-ci-cpp-test_%CONFIG%.zip
    name: mainApp

 
deploy:
  #release: travis-ci-cpp-test-v$(appveyor_build_version)
  #description: 'travis-ci-cpp-test'
  provider: GitHub
  auth_token:
    secure: G2wXH4E4jgi6ykt7BLKJsZ5WvBxQ4kjIwK4YeCf/gmEYBiTqpNjctkd4XotPsKq6 # your encrypted token from GitHub
  artifact: mainApp            # upload artifact
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true           # deploy on tag push only
    branch: /v\d\.\d\.\d/
    #branch: $(appveyor_repo_tag_name)  # release from master branch only

